struct params{
  pic_nrows: i32,
  pic_ncols: i32,
  composite_nrows: i32,
  composite_ncols: i32,
  // constant_nrows: i32,
  // constant_ncols: i32,
  circle_nrows: i32,
  circle_ncols: i32,
  dilation_nrows: i32,
  dilation_ncols: i32,
  max_iterations: u32,
  threshold: f32,
  minmass: f32,
}
