struct Params{
  pic_nrows: i32,
  pic_ncols: i32,
  preprocess_nrows: i32,
  preprocess_ncols: i32,
  sigma2: f32,
  // constant_nrows: i32,
  // constant_ncols: i32,
  circle_nrows: i32,
  circle_ncols: i32,
  dilation_nrows: i32,
  dilation_ncols: i32,
  max_iterations: u32,
  threshold: f32,
  minmass: f32,
  margin: i32,
  snr: f32,
  minmass_snr: f32,
  rough_snr_factor: f32,
}
