[package]
name = "gpu-tracking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "gpu_tracking"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "tracking"
path = "src/main.rs"

[features]
python = ["pyo3", "numpy"]

[dependencies]
ndarray = "0.15.6"
rayon = "1.5.3"
tiff = "0.7.3"
wgpu = "0.13.1"
anyhow = "1.0.65"
pollster = "0.2.5"
bytemuck = "1.12.1"
futures = "0.3.24"
image = "0.24.4"
futures-intrusive = "0.4.0"
clap = { version = "4.0.6", features = ["derive"] }
pyo3 = { version = "0.17.1", features = ["extension-module"], optional = true}
numpy = { version = "0.17.2", optional = true }
ndarray-csv = "0.5.1"
