[package]
edition = "2021"
name = "gpu-tracking"
version = "0.1.0"
[[bin]]
name = "tracking"
path = "src/main.rs"

[features]
python = ["pyo3", "numpy"]

[dependencies]
anyhow = "1.0.65"
bytemuck = "1.12.1"
futures = "0.3.24"
futures-intrusive = "0.4.0"
image = "0.24.4"
kd-tree = "*"
ndarray = "0.15.6"
ndarray-csv = "0.5.1"
numpy = { version = "0.17.2", optional = true  }
pyo3 = { version = "0.17.1", features = ["extension-module"], optional = true }
pollster = "0.2.5"
rayon = "1.5.3"
tiff = "0.7.3"
wgpu = "0.13.1"
num-traits = "0.2.15"
typenum = "1.15.0"

[dependencies.clap]
features = ["derive"]
version = "4.0.6"

[lib]
crate-type = ["cdylib", "rlib"]
name = "gpu_tracking"
